version: '3.7'

networks:
  example:
    driver: overlay

services:
  axon-server:
    image: axoniq/axonserver:${AXON_VERSION}
    networks:
    - example
    ports:
    - target: 8024
      published: ${AXON_SERVER_PORT}
    expose:
    - "8024"
    - "8124"
    volumes:
    -
      type: volume
      source: axon-data
      target: /opt/axonserver/data
  example:
    image: jeroenvm/archetype-nix-go
    working_dir: ${PROJECT}
    command:
      - "target/bin/example"
    hostname: example
    networks:
    - example
    ports:
    - target: 8181
      published: ${API_SERVER_PORT}
    depends_on:
    - axon-server
    volumes:
      - type: volume
        source: jeroenvm-nix-store
        target: /nix/store
#${EXTRA_VOLUMES}

volumes:
  axon-data:
  jeroenvm-nix-store:
    external: true

